ITEMS = [
    {
        "id": "ai-foundations-remote",
        "name": "AI Foundations Sprint",
        "category": "AI/ML",
        "description": "Four-week applied AI sprint for students who know Python basics.",
        "min_age": 18,
        "max_age": 28,
        "education_levels": ["undergraduate", "graduate", "self-taught"],
        "cities": ["Pune", "Mumbai", "Bengaluru"],
        "remote_allowed": True,
        "required_skills": ["python"],
        "preferred_skills": ["numpy", "pandas", "statistics"],
        "min_experience_months": 0,
        "fee_inr": 0,
        "min_weekly_hours": 8,
        "interests": ["machine learning", "data"],
        "requires_laptop": True,
        "starts_within_days": 14,
        "active": True,
    },
    {
        "id": "backend-api-lab-pune",
        "name": "Backend API Lab",
        "category": "Backend",
        "description": "Onsite lab focused on REST APIs, data modelling, and review habits.",
        "min_age": 18,
        "max_age": 30,
        "education_levels": ["undergraduate", "graduate", "self-taught"],
        "cities": ["Pune"],
        "remote_allowed": False,
        "required_skills": ["javascript"],
        "preferred_skills": ["node", "sql", "testing"],
        "min_experience_months": 2,
        "fee_inr": 0,
        "min_weekly_hours": 12,
        "interests": ["apis", "databases"],
        "requires_laptop": True,
        "starts_within_days": 21,
        "active": True,
    },
    {
        "id": "frontend-product-studio",
        "name": "Frontend Product Studio",
        "category": "Frontend",
        "description": "UI engineering track for building polished product workflows.",
        "min_age": 17,
        "max_age": 27,
        "education_levels": ["undergraduate", "graduate", "self-taught"],
        "cities": ["Pune", "Nashik"],
        "remote_allowed": True,
        "required_skills": ["html", "css", "javascript"],
        "preferred_skills": ["react", "accessibility", "figma"],
        "min_experience_months": 1,
        "fee_inr": 0,
        "min_weekly_hours": 10,
        "interests": ["ui", "product"],
        "requires_laptop": True,
        "starts_within_days": 10,
        "active": True,
    },
    {
        "id": "data-ops-apprenticeship",
        "name": "Data Operations Apprenticeship",
        "category": "Data",
        "description": "Practical track for cleaning, validating, and reporting operational data.",
        "min_age": 18,
        "max_age": 32,
        "education_levels": ["undergraduate", "graduate"],
        "cities": ["Pune", "Mumbai"],
        "remote_allowed": False,
        "required_skills": ["excel"],
        "preferred_skills": ["sql", "python", "dashboards"],
        "min_experience_months": 0,
        "fee_inr": 0,
        "min_weekly_hours": 15,
        "interests": ["data", "operations"],
        "requires_laptop": True,
        "starts_within_days": 7,
        "active": True,
    },
    {
        "id": "ml-research-reading-group",
        "name": "ML Research Reading Group",
        "category": "AI/ML",
        "description": "Small cohort for reading papers and reproducing simple experiments.",
        "min_age": 20,
        "max_age": 35,
        "education_levels": ["graduate"],
        "cities": ["Pune", "Bengaluru", "Hyderabad"],
        "remote_allowed": True,
        "required_skills": ["python", "statistics"],
        "preferred_skills": ["pytorch", "linear algebra", "papers"],
        "min_experience_months": 6,
        "fee_inr": 3000,
        "min_weekly_hours": 6,
        "interests": ["machine learning", "research"],
        "requires_laptop": True,
        "starts_within_days": 30,
        "active": True,
    },
    {
        "id": "qa-automation-track",
        "name": "QA Automation Track",
        "category": "Testing",
        "description": "Automation-first testing program for web products.",
        "min_age": 18,
        "max_age": 30,
        "education_levels": ["undergraduate", "graduate", "self-taught"],
        "cities": ["Pune", "Nagpur"],
        "remote_allowed": True,
        "required_skills": ["javascript"],
        "preferred_skills": ["playwright", "testing", "apis"],
        "min_experience_months": 0,
        "fee_inr": 1000,
        "min_weekly_hours": 8,
        "interests": ["testing", "quality"],
        "requires_laptop": True,
        "starts_within_days": 14,
        "active": True,
    },
    {
        "id": "cloud-basics-bootcamp",
        "name": "Cloud Basics Bootcamp",
        "category": "Cloud",
        "description": "Introductory bootcamp for deploying simple services safely.",
        "min_age": 18,
        "max_age": 34,
        "education_levels": ["undergraduate", "graduate", "self-taught"],
        "cities": ["Pune", "Mumbai", "Delhi"],
        "remote_allowed": True,
        "required_skills": ["linux"],
        "preferred_skills": ["docker", "apis", "networking"],
        "min_experience_months": 1,
        "fee_inr": 2500,
        "min_weekly_hours": 7,
        "interests": ["cloud", "devops"],
        "requires_laptop": True,
        "starts_within_days": 28,
        "active": True,
    },
    {
        "id": "no-code-ops-builder",
        "name": "No-Code Ops Builder",
        "category": "Operations",
        "description": "Workflow automation track using spreadsheets, forms, and light scripting.",
        "min_age": 16,
        "max_age": 40,
        "education_levels": ["school", "undergraduate", "graduate", "self-taught"],
        "cities": ["Pune", "Mumbai", "Remote"],
        "remote_allowed": True,
        "required_skills": ["excel"],
        "preferred_skills": ["automation", "documentation"],
        "min_experience_months": 0,
        "fee_inr": 0,
        "min_weekly_hours": 5,
        "interests": ["operations", "productivity"],
        "requires_laptop": False,
        "starts_within_days": 5,
        "active": True,
    },
    {
        "id": "cyber-hygiene-workshop",
        "name": "Cyber Hygiene Workshop",
        "category": "Security",
        "description": "Beginner-friendly security basics for students and support teams.",
        "min_age": 18,
        "max_age": 35,
        "education_levels": ["undergraduate", "graduate", "self-taught"],
        "cities": ["Pune", "Mumbai", "Hyderabad"],
        "remote_allowed": True,
        "required_skills": ["linux"],
        "preferred_skills": ["networking", "documentation"],
        "min_experience_months": 0,
        "fee_inr": 1500,
        "min_weekly_hours": 4,
        "interests": ["security", "systems"],
        "requires_laptop": True,
        "starts_within_days": 12,
        "active": True,
    },
    {
        "id": "analytics-dashboard-clinic",
        "name": "Analytics Dashboard Clinic",
        "category": "Analytics",
        "description": "Build dashboards around real product and operations questions.",
        "min_age": 18,
        "max_age": 32,
        "education_levels": ["undergraduate", "graduate"],
        "cities": ["Pune", "Mumbai", "Bengaluru"],
        "remote_allowed": True,
        "required_skills": ["excel"],
        "preferred_skills": ["sql", "power bi", "statistics"],
        "min_experience_months": 2,
        "fee_inr": 2000,
        "min_weekly_hours": 8,
        "interests": ["data", "dashboards"],
        "requires_laptop": True,
        "starts_within_days": 18,
        "active": True,
    },
    {
        "id": "mobile-web-starter",
        "name": "Mobile Web Starter",
        "category": "Frontend",
        "description": "Responsive web basics with practical layout and browser testing.",
        "min_age": 16,
        "max_age": 25,
        "education_levels": ["school", "undergraduate", "self-taught"],
        "cities": ["Pune", "Nashik", "Kolhapur"],
        "remote_allowed": True,
        "required_skills": ["html", "css"],
        "preferred_skills": ["javascript", "accessibility"],
        "min_experience_months": 0,
        "fee_inr": 500,
        "min_weekly_hours": 6,
        "interests": ["ui", "web"],
        "requires_laptop": False,
        "starts_within_days": 8,
        "active": True,
    },
    {
        "id": "sql-for-product-teams",
        "name": "SQL for Product Teams",
        "category": "Data",
        "description": "Query-writing practice for product decisions and audit trails.",
        "min_age": 18,
        "max_age": 36,
        "education_levels": ["undergraduate", "graduate", "self-taught"],
        "cities": ["Pune", "Remote"],
        "remote_allowed": True,
        "required_skills": ["excel"],
        "preferred_skills": ["sql", "analytics"],
        "min_experience_months": 0,
        "fee_inr": 1200,
        "min_weekly_hours": 5,
        "interests": ["data", "product"],
        "requires_laptop": True,
        "starts_within_days": 14,
        "active": True,
    },
    {
        "id": "devops-incident-sim",
        "name": "DevOps Incident Simulation",
        "category": "DevOps",
        "description": "Incident response exercises for students with basic cloud exposure.",
        "min_age": 20,
        "max_age": 35,
        "education_levels": ["undergraduate", "graduate", "self-taught"],
        "cities": ["Pune", "Bengaluru"],
        "remote_allowed": False,
        "required_skills": ["linux", "docker"],
        "preferred_skills": ["cloud", "networking", "monitoring"],
        "min_experience_months": 6,
        "fee_inr": 3500,
        "min_weekly_hours": 10,
        "interests": ["devops", "systems"],
        "requires_laptop": True,
        "starts_within_days": 20,
        "active": True,
    },
    {
        "id": "product-writing-for-builders",
        "name": "Product Writing for Builders",
        "category": "Product",
        "description": "Documentation and release-note practice for engineering students.",
        "min_age": 17,
        "max_age": 32,
        "education_levels": ["undergraduate", "graduate", "self-taught"],
        "cities": ["Pune", "Mumbai", "Remote"],
        "remote_allowed": True,
        "required_skills": ["documentation"],
        "preferred_skills": ["product", "research"],
        "min_experience_months": 0,
        "fee_inr": 0,
        "min_weekly_hours": 4,
        "interests": ["product", "writing"],
        "requires_laptop": False,
        "starts_within_days": 6,
        "active": True,
    },
    {
        "id": "computer-vision-mini-lab",
        "name": "Computer Vision Mini Lab",
        "category": "AI/ML",
        "description": "Hands-on image classification exercises with a small dataset.",
        "min_age": 19,
        "max_age": 30,
        "education_levels": ["undergraduate", "graduate"],
        "cities": ["Pune", "Bengaluru", "Hyderabad"],
        "remote_allowed": True,
        "required_skills": ["python", "numpy"],
        "preferred_skills": ["pytorch", "opencv", "statistics"],
        "min_experience_months": 3,
        "fee_inr": 4000,
        "min_weekly_hours": 9,
        "interests": ["machine learning", "computer vision"],
        "requires_laptop": True,
        "starts_within_days": 25,
        "active": True,
    },
]
